### ISSUE TITLE
Share the best sakura-chan image on twitter

### ISSUE THREAD

**Issue by miyamoen** [elm-jp/elm-jp.github.io#2]
Hi

We will share a **large** sakura-chan image on twitter card.
But, we have a big probrem!

Check `https://miyamoen.github.io/elm-jp.github.io/` with [Twitter Card validator](https://cards-dev.twitter.com/validator):

![image](https://user-images.githubusercontent.com/13114545/51982520-99e5fb00-24d9-11e9-9730-1c7d83fa358d.png)

OMG!
Sakura-chan is out of screen!

You have a fitter image?

Thanks.

**Comment by arowM** [comment]
Good point!
I've deployed cropped image in `img/card.jpg`.
![card](https://user-images.githubusercontent.com/1481749/51987597-357d6880-24e6-11e9-8965-5088ada0d06f.jpg)

Could you create a PR for adding extra twitter tags (e.g., "twitter:description").

P.S. Also I've changed community explanation to make an excuse why our site is filled with sakura-chan images.

**Comment by arowM** [comment]
Oops, I've just found #3.

**Comment by arowM** [comment]
Merged #3.
