### ISSUE TITLE
Elm Meetup（第1回オンライン開催）の準備

### ISSUE THREAD

**Issue by negiboudu** [elm-jp/elm-jp.github.io#22]
https://elm-jp.connpass.com/event/262458/

# 当日までの準備
- [x] 発表者を募集する（TBD枠を埋める）
    - OK
- [x] Zoomを用意する
    - OK
- [x] 発表者に準備物をお伝えしておく
    - このあと戸塚から連絡します
- [x] 録画するならば用意しておく（Zoom録画するならば事前に周知しておいた方が良さそう）
    - 録画しない
- [x] リアルタイム配信するならば用意しておく
    - しない
    - 負荷分散の利点あるかもしれないけど、今回の人数であればZoomで充分

# 当日の役割分担
- [x] 司会進行
   - 戸塚
- [x] タイムキーパー
   - 戸塚
- [x] 問い合わせ窓口
   - ねぎぼうづ、さくらちゃん
   - DiscordとTwitterハッシュタグ `#elmjp` で受け付ける
- [x] 盛り上げ役？
   - 質問があれば積極的にお願いします
   - 発表者の人は常時顔出ししてもらう（任意）
      - Zoomが重くならなければ一般参加の人もOK
      
      
# 懇親会どうする？

- 会場分散する？（Gatherなど）
- アンケートをリアルタイムに取っていくでも
- 懇親会の目的は？
   - 自分を知ってもらいたい or 聞きたい

**Comment by arowM** [comment]
Zoomはホスト側が無料版使っていると40分制限があるので、有償版を用意する必要がありそうですね！
https://zoom.us/pricing

**Comment by negiboudu** [comment]
あと、15時からの懇親会の内容も気になっています。どんなことをするのかなあと。

**Comment by y047aka** [comment]
> Zoomはホスト側が無料版使っていると40分制限があるので、有償版を用意する必要がありそうですね！

Zoomは所属会社のアカウントを使わせてもらえそうです！

**Comment by y047aka** [comment]
イベント終了しているのでcloseしますね。
ご協力ありがとうございました！
